name: ThornyaAPI
version: ${project.version}
main: thornyaplugin.thornyaplugin.ThornyaPlugin
api-version: 1.16
authors: [ Gusttavo13 ]
description: Plugin integration Thornya
website: https://thornya.club
softdepend:
  - SimpleClans
  - Essentials
depend:
  - SimpleClans
  - Essentials
commands:
  template:
    description: comandos gerais do thornya

